title: Abdulhakim Bashir
logo: /assets/img/profile.jpeg
description: My E-Portfolio based on work carried out on my Msc Program on Artificial Intelligence and Machine Learning at the University of Essex.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
